### PR TITLE
Add a few missing workbench colours

### PR DESCRIPTION
**Pull request by liamsheppard**
Hey @torodovitch, I'm not able to build the theme file, am I doing something wrong?

I'm trying to run this task,

image

And I'm getting this error

image

Do I need to run the builder extension first? I feel like I've most likely missed something.

image

image

If I'm not doing anything wrong, would you mind building the new theme from my changes here?

### CODE REVIEW

**Comment by torodovitch** [comment]
That's my bad, I'm on it.

**Comment by torodovitch** [comment]
Ok, so, first I was a bit too aggressive on the whole node_modules ignoring. With the changes from https://github.com/liamsheppard/voodoo-theme/commit/c15002b9dc88786312db4ae35d281677897206a3, strip-json-comments _should_ be shipped with the extension next time you publish an update and everything should work out of the box.

Now, for the fun part, I just realise how silent vscode extensions are. On my end, I couldn't get it to give any sign of life until I executed it in debug and realised I was missing the strip-json-comments module. Just to confirm, can you try and run `yarn install` and then try to build the theme file? Also didn't build/push the changes you made since anyway I want to make sure you're comfortable using the damn thing 'cause you the one who rocks. :rocket: :rocket: :rocket: :rocket:

**Comment by liamsheppard** [comment]
Hmm, it's still failing with the same errors, it can't find the files.

Wonder if this might be caused by us running a different OS? I'm on a mac.

**Comment by torodovitch** [comment]
Oh right, that might be an issue. The builder is using the extension's path as root, not the active workspace's. If you work in a different folder, e.g. a clone of this repo in Documents, it'll still build the theme-src.json from `~/.vscode/extensions/whatever-folder-containing-voodoo`.

So you need to make sure you have the necessary `node_modules` available over there and for the build to work you'll need to edit the theme-src.json in that folder as well.

Also, I'm booked all week, but I'll try to review the extension's workflow this weekend. With the pandemic, I've been stuck using JetBrains' stuff behind a VPN and I never got time to really try out the builder like I wanted to.

**Comment by liamsheppard** [comment]
Ahhhhh, that's probably it. I'll have another go.

No rush at all btw this is not super important

**Comment by torodovitch** [comment]
The builder should be working with the `themes/theme-src.json` and `themes/Voodoo-color-theme.json` from the active workspace now, tho you still need to make sure you're using the latest version in the extension's folder under `~/.vscode/extensions`.

**Pull request merged**
